language: php

php:
  - 5.4

env:
  global:
    - secure: "FZJA/WJSKeVfJPafI6Yco6+66Oa7ezt7WQ80ggPuW9psQttQhG6IiQ0WdNgT\nYe0oitrRN62UBcnY1W1H2R0hqT0G8chmBP076AZ0UJ/aUdl1ZTmDiSs/YWz6\nb3q3JryoMdP8MNJNPi6qVRkhGK8D1iapcN8aicoRKL1+xwTja5s="
    - secure: "EIxZfB0V0kn2CZ+0Qc4guqE2LwXYFOZHDM0720wVwi8FOKBYT6xQP+hBodrQ\nzJqhLW+SiexomCv5fUgX0oyjbcoxKJj19SSb76cVy5RAzqdg/agMpMNTQpI9\nXjnBV6Tt9edBNOxP08QxGRJRIekd1amDKCq0fisdxfIWSGvHENc="

mysql:
  database: drupal
  username: root
  encoding: utf8

install:

  # Create MySQL Database
  - mysql -e 'create database drupal;'
  - sudo apt-get --quiet=2 install php5-cli php5-cgi php5-curl php5-gd php5-mysql > /dev/null

  # Install Drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash

  # Run composer
  - cd ./tests/behat
  - composer install
  - cd ../../

before_script:

  # Install Kickstart Profile
  - drush make --prepare-install build-commerce-kickstart.make kickstart --yes
  - cd kickstart
  - sudo chmod -R 777 sites/all/
  - sudo chmod -R 777 sites/default/files/
  - drush si commerce_kickstart --sites-subdir=default --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Commerce Kickstart Profile" --yes
  - drush cc all --yes
  - cd ../

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5s

  # Run the drush built in webserver.
  - sudo chmod u+x /home/travis/.phpenv/shims/drush
  - sudo ln -s /home/travis/.phpenv/shims/drush /usr/bin/drush
  - sudo drush --root=$PWD/kickstart runserver --server=builtin 80 &
  - sleep 5s # give Web server some time to bind to sockets, etc

  # Run selenium
  #- wget http://selenium.googlecode.com/files/selenium-server-standalone-2.25.0.jar
  #- java -jar selenium-server-standalone-2.25.0.jar -p 4444 > /dev/null 2>&1 &
  #- sleep 5s

script:
  - cd tests/behat

  # Set env variable for behat params.
  - export BEHAT_PARAMS="extensions[Behat\MinkExtension\Extension][selenium2][wd_host]=$SAUCE_USERNAME:$SAUCE_ACCESS_KEY@ondemand.saucelabs.com/wd/hub"

  # Setup sauce tunnel in the background and give it time to launch.
  - java -jar vendor/sauce/connect/lib/Sauce-Connect.jar -P 4445 $SAUCE_USERNAME $SAUCE_ACCESS_KEY > /dev/null 2>&1 &
  - sleep 45s

  # behat.yml includes behat.local.yml so it must exist
  - touch behat.local.yml

  # Run behat tests
  #- ./bin/behat --no-paths
  - ./bin/behat -p Firefox-14 --no-paths

  # Shut down the sauce tunnel
  - kill $(ps aux | grep "Sauce-Connect" | grep -v 'grep' | awk '{print $2}')

